### ISSUE TITLE
fatal: clone of 'git@github.com:cuihenggang/caffe.git' into submodule path 'apps/caffe' failed

### ISSUE THREAD

**Issue by xingzhaoo** [cuihenggang/geeps#3]
Hi,

I followed "git clone --recurse-submodules https://github.com/cuihenggang/geeps.git" to install geeps but received the following message. Is there any work around to get caffe or set the permission of caffe the same as geeps.git?

Submodule 'apps/caffe' (git@github.com:cuihenggang/caffe.git) registered for path 'apps/caffe'
Cloning into 'apps/caffe'...
Warning: Permanently added 'github.com,xxx.xxx.xxx.xxx' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:cuihenggang/caffe.git' into submodule path 'apps/caffe' failed

Thanks

**Comment by lcytzk** [comment]
you can clone manually

**Comment by raajay** [comment]
A principled way is the change the sub-module dependency from git@github.com:cuihenggang/caffe.git to https://github.com/cuihenggang/caffe.git . After you clone, make the above change in .gitmodules and .git/config. "git submodule update --init" should work file after that.

**Comment by xingzhaoo** [comment]
Thanks a lot, raajay. I followed your steps. The problem is solved.

**Comment by cuihenggang** [comment]
@raajay Thank you for answering xingzhaoo's question. Do you think I need to change the submodule files, to make it easier for the users?
